# Generated by Django 6.0.2 on 2026-08-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('CREATE', 'Create'), ('READ', 'Read/View'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RESTORE', 'Restore'), ('SURVEY_SUBMIT', 'Survey Submitted'), ('SURVEY_ASSIGN', 'Survey Assigned'), ('SURVEY_VERIFY', 'Survey Verified'), ('SURVEY_REJECT', 'Survey Rejected'), ('EXPORT', 'Data Export'), ('IMPORT', 'Data Import'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete'), ('FILE_UPLOAD', 'File Upload'), ('FILE_DOWNLOAD', 'File Download'), ('FILE_DELETE', 'File Delete'), ('SETTINGS_CHANGE', 'Settings Changed'), ('ROLE_ASSIGNED', 'Role Assigned'), ('PERMISSION_CHANGED', 'Permission Changed')], db_index=True, max_length=50),
        ),
    ]
