# Generated by Django 6.0 on 2026-02-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintypeofcare',
            name='is_healthcare',
            field=models.BooleanField(default=True, help_text='True for healthcare facilities (R/D/O/A/I), False for non-healthcare (SR/SD/SO/SA/SI)'),
        ),
        migrations.AddField(
            model_name='maintypeofcare',
            name='level',
            field=models.IntegerField(default=0, help_text='Hierarchy depth: 0=root, 1=first level, 2=second level, etc.'),
        ),
        migrations.AddField(
            model_name='maintypeofcare',
            name='service_delivery_type',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'Residential'), ('DAY_CARE', 'Day Care'), ('OUTPATIENT', 'Outpatient'), ('ACCESSIBILITY', 'Accessibility'), ('INFORMATION', 'Information')], help_text='Main service delivery mode', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintypeofcare',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='maintypeofcare',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='maintypeofcare',
            index=models.Index(fields=['is_healthcare', 'is_active'], name='mtc_classif_is_heal_949a84_idx'),
        ),
        migrations.AddIndex(
            model_name='maintypeofcare',
            index=models.Index(fields=['service_delivery_type', 'is_active'], name='mtc_classif_service_f64e88_idx'),
        ),
    ]
