# Generated by Django 6.0 on 2026-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_add_desde_ltc_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriFasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('facility_type', models.CharField(choices=[('KESEHATAN', 'Fasilitas Kesehatan'), ('NON_KESEHATAN', 'Non Kesehatan')], default='KESEHATAN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori Fasilitas',
                'verbose_name_plural': 'Kategori Fasilitas',
                'db_table': 'kategori_fasilitas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='KategoriLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori Layanan',
                'verbose_name_plural': 'Kategori Layanan',
                'db_table': 'kategori_layanan',
                'ordering': ['code'],
            },
        ),
    ]
