# Generated by Django 6.0 on 2026-03-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_kategorifasilitas_kategorilayanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicstableinputsofcare',
            name='kategori_fasilitas',
            field=models.CharField(blank=True, choices=[('KESEHATAN', 'Fasilitas Kesehatan'), ('NON_KESEHATAN', 'Non Kesehatan')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='basicstableinputsofcare',
            name='kategori_layanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bsic_categories', to='directory.kategorilayanan'),
        ),
    ]
