# Generated by Django 6.0.2 on 2026-03-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_basicstableinputsofcare_kategori_fasilitas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='kecamatan',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
