# Generated by Django 6.0.2 on 2026-04-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_service_kecamatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicstableinputsofcare',
            name='full_label',
            field=models.TextField(blank=True, help_text='Label lengkap hierarki DESDE-LTC, e.g. Layanan Rawat Inap, Akut, Rumah Sakit'),
        ),
    ]
