# Generated by Django 6.0.2 on 2026-06-19 02:13

import django.db.models.deletion
from django.db import migrations, models


def seed_sektor_service_types(apps, schema_editor):
    ServiceType = apps.get_model('directory', 'ServiceType')
    for name in ('Faskes', 'Non Faskes'):
        ServiceType.objects.get_or_create(name=name, defaults={'is_active': True})


def unseed_sektor_service_types(apps, schema_editor):
    ServiceType = apps.get_model('directory', 'ServiceType')
    ServiceType.objects.filter(name__in=('Faskes', 'Non Faskes')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_basicstableinputsofcare_full_label'),
    ]

    operations = [
        migrations.RunPython(seed_sektor_service_types, unseed_sektor_service_types),
        migrations.AlterField(
            model_name='service',
            name='bsic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='directory.basicstableinputsofcare'),
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='mtc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='directory.maintypeofcare'),
        ),
        migrations.AlterField(
            model_name='service',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='directory.servicetype'),
        ),
    ]
