# Generated by Django 6.0.2 on 2026-09-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0051_backfill_published_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Agency the table came from, e.g. "Dinkes Kabupaten Kebumen"', max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Visible on the public kecamatan pages and the map')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'secondary_datasets',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='jiwa', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_population', models.BooleanField(default=False)),
                ('is_aggregate', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='secondary.secondarydataset')),
            ],
            options={
                'db_table': 'secondary_indicators',
                'ordering': ['dataset', 'order', 'name'],
                'unique_together': {('dataset', 'code')},
            },
        ),
        migrations.CreateModel(
            name='KecamatanIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_male', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_female', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('kecamatan', models.ForeignKey(limit_choices_to={'level': 'KECAMATAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_values', to='survey.geographicunit')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='secondary.secondaryindicator')),
            ],
            options={
                'db_table': 'secondary_kecamatan_values',
                'ordering': ['indicator', 'kecamatan__name'],
                'unique_together': {('indicator', 'kecamatan')},
            },
        ),
    ]
