# Generated by Django 6.0 on 2025-12-13 08:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField(db_index=True)),
                ('survey_period_start', models.DateField()),
                ('survey_period_end', models.DateField()),
                ('surveyor_notes', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verifier_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('current_bed_capacity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('beds_occupied', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_staff_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_psychiatrist_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_psychologist_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_nurse_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_social_worker_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_patients_served', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_patients', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('returning_patients', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('patients_male', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('patients_female', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('patients_age_0_17', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('patients_age_18_64', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('patients_age_65_plus', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('patient_satisfaction_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('average_wait_time_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bpjs_patients', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('private_insurance_patients', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('self_pay_patients', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('challenges_faced', models.TextField(blank=True)),
                ('improvements_needed', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_verifier', models.ForeignKey(blank=True, limit_choices_to={'role': 'VERIFIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_to_verify', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='directory.service')),
                ('surveyor', models.ForeignKey(limit_choices_to={'role': 'SURVEYOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='surveys_conducted', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'VERIFIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveys',
                'ordering': ['-survey_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='survey_attachments/%Y/%m/')),
                ('attachment_type', models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='PHOTO', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='survey.survey')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned to Verifier'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted')], max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], max_length=20)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='survey.survey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['service', '-survey_date'], name='surveys_service_fa4c69_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['surveyor', '-survey_date'], name='surveys_surveyo_6f7978_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['verification_status', '-survey_date'], name='surveys_verific_8f18eb_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['assigned_verifier', 'verification_status'], name='surveys_assigne_3e0b06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('service', 'survey_date')},
        ),
        migrations.AddIndex(
            model_name='surveyauditlog',
            index=models.Index(fields=['survey', '-timestamp'], name='survey_audi_survey__23602b_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='survey_audi_action_e5db00_idx'),
        ),
    ]
