# Generated by Django 6.0 on 2025-12-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='location_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True),
        ),
    ]
