# Generated by Django 6.0 on 2025-12-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_latitude_survey_location_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude coordinate', max_digits=11, null=True),
        ),
    ]
