# Generated by Django 6.0 on 2026-02-05 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_add_desde_ltc_fields'),
        ('survey', '0003_alter_survey_latitude_alter_survey_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('introduction_text', models.TextField(blank=True)),
                ('show_condition', models.JSONField(blank=True, help_text='JSON condition: {"question_code": "Q3", "operator": "equals", "value": "KESEHATAN"}', null=True)),
            ],
            options={
                'db_table': 'survey_question_sections',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DynamicSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField(db_index=True)),
                ('surveyor_notes', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verifier_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('location_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_verifier', models.ForeignKey(blank=True, limit_choices_to={'role': 'VERIFIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_surveys_to_verify', to=settings.AUTH_USER_MODEL)),
                ('derived_mtc_codes', models.ManyToManyField(blank=True, help_text='MTC codes derived from questionnaire answers', related_name='derived_from_responses', to='directory.maintypeofcare')),
                ('linked_survey', models.ForeignKey(blank=True, help_text='Link to structured survey if this extends it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_responses', to='survey.survey')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_survey_responses', to='directory.service')),
                ('surveyor', models.ForeignKey(limit_choices_to={'role': 'SURVEYOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='dynamic_surveys_conducted', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_surveys_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dynamic_survey_responses',
                'ordering': ['-survey_date'],
            },
        ),
        migrations.CreateModel(
            name='GeographicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('level', models.CharField(choices=[('PROVINSI', 'Provinsi'), ('KABUPATEN_KOTA', 'Kabupaten/Kota'), ('KECAMATAN', 'Kecamatan'), ('DESA_KELURAHAN', 'Desa/Kelurahan')], db_index=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='survey.geographicunit')),
            ],
            options={
                'db_table': 'geographic_units',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('question_text', models.TextField()),
                ('answer_type', models.CharField(choices=[('TEXT', 'Teks'), ('TEXTAREA', 'Teks Panjang'), ('NUMBER', 'Angka'), ('INTEGER', 'Bilangan Bulat'), ('DATE', 'Tanggal'), ('TIME', 'Waktu'), ('BOOLEAN', 'Ya/Tidak'), ('SINGLE_CHOICE', 'Pilihan Tunggal'), ('MULTIPLE_CHOICE', 'Pilihan Ganda'), ('GEO_PROVINSI', 'Pilih Provinsi'), ('GEO_KABUPATEN', 'Pilih Kabupaten/Kota'), ('GEO_KECAMATAN', 'Pilih Kecamatan'), ('GEO_DESA', 'Pilih Desa/Kelurahan'), ('GEO_FULL', 'Alamat Lengkap (Provinsi s/d Desa)'), ('COVERAGE_LEVEL', 'Tingkat Cakupan Wilayah'), ('PHONE', 'Nomor Telepon'), ('EMAIL', 'Email'), ('URL', 'Website'), ('FILE', 'Upload File'), ('GPS', 'Koordinat GPS'), ('STAFF_TABLE', 'Tabel Data Staf'), ('DIAGNOSIS_TABLE', 'Tabel Diagnosis')], max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('desde_ltc_description', models.TextField(blank=True, help_text='DESDE-LTC specific description for this question')),
                ('keterangan', models.TextField(blank=True, help_text='Detailed explanation/instructions')),
                ('validation_rules', models.JSONField(blank=True, help_text='JSON: {"min": 0, "max": 100, "pattern": "regex", "max_length": 500}', null=True)),
                ('show_condition', models.JSONField(blank=True, help_text='JSON: {"question_code": "Q2", "operator": "equals", "value": "YA"}', null=True)),
                ('skip_logic', models.JSONField(blank=True, help_text='JSON: [{"value": "YA", "goto": "RQ2"}, {"value": "TIDAK", "goto": "RQ5"}]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mtc_code', models.ForeignKey(blank=True, help_text='The MTC code this question helps determine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='directory.maintypeofcare')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.questionsection')),
            ],
            options={
                'db_table': 'survey_questions',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('keterangan', models.TextField(blank=True)),
                ('next_question_code', models.CharField(blank=True, max_length=50)),
                ('has_other_input', models.BooleanField(default=False)),
                ('other_input_label', models.CharField(blank=True, default='Sebutkan', max_length=100)),
                ('mtc_code', models.ForeignKey(blank=True, help_text='MTC code derived when this choice is selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_choices', to='directory.maintypeofcare')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question')),
            ],
            options={
                'db_table': 'survey_question_choices',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('time_value', models.TimeField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(null=True)),
                ('other_text', models.TextField(blank=True, help_text='For "Lainnya, sebutkan" answers')),
                ('coverage_level', models.CharField(blank=True, choices=[('DESA_KELURAHAN', 'Desa/Kelurahan'), ('KECAMATAN', 'Kecamatan'), ('KABUPATEN_KOTA', 'Kabupaten/Kota'), ('PROVINSI', 'Provinsi'), ('NASIONAL', 'Nasional')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='survey_answers/%Y/%m/')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('table_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('derived_mtc', models.ForeignKey(blank=True, help_text='MTC code derived from this answer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_from_answers', to='directory.maintypeofcare')),
                ('geographic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='survey.geographicunit')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='survey.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.dynamicsurveyresponse')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='survey.questionchoice')),
            ],
            options={
                'db_table': 'survey_question_answers',
                'ordering': ['response', 'question__section__order', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('template_type', models.CharField(choices=[('RESIDENTIAL', 'Rawat Inap (R)'), ('DAY_CARE', 'Rawat Harian (D)'), ('OUTPATIENT', 'Rawat Jalan (O)'), ('ACCESSIBILITY', 'Aksesibilitas (A)'), ('INFORMATION', 'Informasi (I)'), ('BASIC_DATA', 'Data Dasar'), ('GENERAL', 'Umum')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('target_mtc', models.ForeignKey(blank=True, help_text='The MTC type this template helps classify (R, D, O, A, I)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_templates', to='directory.maintypeofcare')),
            ],
            options={
                'db_table': 'survey_templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='questionsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='survey.surveytemplate'),
        ),
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='survey.surveytemplate'),
        ),
        migrations.AddIndex(
            model_name='geographicunit',
            index=models.Index(fields=['level', 'parent'], name='geographic__level_12fc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicunit',
            index=models.Index(fields=['parent', 'name'], name='geographic__parent__53e3ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('response', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('section', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='questionsection',
            unique_together={('template', 'code')},
        ),
        migrations.AddIndex(
            model_name='dynamicsurveyresponse',
            index=models.Index(fields=['template', '-survey_date'], name='dynamic_sur_templat_25e348_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsurveyresponse',
            index=models.Index(fields=['surveyor', '-survey_date'], name='dynamic_sur_surveyo_275413_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsurveyresponse',
            index=models.Index(fields=['verification_status', '-survey_date'], name='dynamic_sur_verific_932feb_idx'),
        ),
    ]
