# Generated by Django 6.0.2 on 2026-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_dynamic_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicsurveyresponse',
            name='verification_status',
            field=models.CharField(choices=[('DRAFT', 'Draf'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='verification_status',
            field=models.CharField(choices=[('DRAFT', 'Draf'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyattachment',
            name='attachment_type',
            field=models.CharField(choices=[('PHOTO', 'Foto'), ('DOCUMENT', 'Dokumen'), ('OTHER', 'Lainnya')], default='PHOTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Dibuat'), ('UPDATED', 'Diperbarui'), ('SUBMITTED', 'Diajukan'), ('ASSIGNED', 'Ditugaskan ke Verifikator'), ('VERIFIED', 'Diverifikasi'), ('REJECTED', 'Ditolak'), ('RESUBMITTED', 'Diajukan Ulang')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyauditlog',
            name='new_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draf'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyauditlog',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draf'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], max_length=20),
        ),
    ]
