# Generated by Django 6.0.2 on 2026-03-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_basicstableinputsofcare_kategori_fasilitas_and_more'),
        ('survey', '0005_alter_dynamicsurveyresponse_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='mtc_code',
            field=models.ForeignKey(blank=True, help_text='BSIC code derived when this choice is selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_choices', to='directory.basicstableinputsofcare'),
        ),
    ]
