# Generated by Django 6.0.2 on 2026-03-09 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_cascade_answer_on_question_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='deletion_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='deletion_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
