# Generated by Django 6.0.2 on 2026-03-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_deletion_request_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='cabang_mtc',
            field=models.CharField(blank=True, help_text='Cabang MTC', max_length=50),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='kode_desde_ltc',
            field=models.CharField(blank=True, help_text='Kode DESDE-LTC (e.g. R.1.1.3)', max_length=20),
        ),
    ]
