# Generated by Django 6.0.2 on 2026-03-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_add_cabang_mtc_kode_desde_ltc_to_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='introduction_text',
            field=models.TextField(blank=True, help_text='Contextual text displayed above this question'),
        ),
    ]
