# Generated by Django 6.0.2 on 2026-03-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_add_repeating_table_answer_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='context_key',
            field=models.CharField(blank=True, default='', help_text='MTC context code for repeated detail questions (e.g. "R2", "R3.1.1")', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('response', 'question', 'context_key')},
        ),
    ]
