# Generated by Django 6.0.2 on 2026-03-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_add_intervention_matrix_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='table_config',
            field=models.JSONField(blank=True, help_text='JSON: {"columns": [{"code": "jabatan", "label": "Jabatan", "type": "text"}, {"code": "l", "label": "L", "type": "number"}]}', null=True),
        ),
    ]
