# Generated by Django 6.0.2 on 2026-04-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_add_operating_hours_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicsurveyresponse',
            name='survey_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
