# Generated by Django 6.0.2 on 2026-04-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_change_survey_date_to_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='other_input_type',
            field=models.CharField(blank=True, default='text', help_text='Data type for other input: text, date, integer, decimal', max_length=20),
        ),
    ]
