# Generated by Django 6.0.2 on 2026-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_add_other_input_type_to_question_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='other_input_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('date', 'Date'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('phone', 'Phone'), ('email', 'Email')], default='text', help_text='Data type for other input', max_length=20),
        ),
    ]
