# Generated by Django 6.0.2 on 2026-04-12 00:45

import apps.survey.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_set_oqb_table_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.survey.models.survey_photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='survey.dynamicsurveyresponse')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_survey_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Photo',
                'verbose_name_plural': 'Survey Photos',
                'db_table': 'survey_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
