# Generated by Django 6.0.2 on 2026-04-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_survey_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the surveyor actually started filling out questions', null=True),
        ),
    ]
