# Generated by Django 6.0.2 on 2026-04-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_basicstableinputsofcare_full_label'),
        ('survey', '0035_fix_trailing_question_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='bsic',
            field=models.ForeignKey(blank=True, help_text='BSIC terkait pilihan ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bsic_question_choices', to='directory.basicstableinputsofcare'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('TEXT', 'Teks'), ('TEXTAREA', 'Teks Panjang'), ('NUMBER', 'Angka'), ('INTEGER', 'Bilangan Bulat'), ('DATE', 'Tanggal'), ('TIME', 'Waktu'), ('BOOLEAN', 'Ya/Tidak'), ('SINGLE_CHOICE', 'Pilihan Tunggal'), ('MULTIPLE_CHOICE', 'Pilihan Ganda'), ('GEO_PROVINSI', 'Pilih Provinsi'), ('GEO_KABUPATEN', 'Pilih Kabupaten/Kota'), ('GEO_KECAMATAN', 'Pilih Kecamatan'), ('GEO_DESA', 'Pilih Desa/Kelurahan'), ('GEO_FULL', 'Alamat Lengkap (Provinsi s/d Desa)'), ('COVERAGE_LEVEL', 'Tingkat Cakupan Wilayah'), ('PHONE', 'Nomor Telepon'), ('EMAIL', 'Email'), ('URL', 'Website'), ('FILE', 'Upload File'), ('GPS', 'Koordinat GPS'), ('STAFF_TABLE', 'Tabel Data Staf'), ('DIAGNOSIS_TABLE', 'Tabel Diagnosis'), ('REPEATING_TABLE', 'Tabel Dinamis (baris berulang)'), ('INTERVENTION_MATRIX', 'Matriks Intervensi (baris pilih + kolom detail)'), ('OPERATING_HOURS', 'Tabel Jadwal')], max_length=30),
        ),
    ]
