# Generated by Django 6.0.2 on 2026-09-14 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_dynamicsurveyresponse_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Visible on the public map and location pages'),
        ),
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicsurveyresponse',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_surveys_published', to=settings.AUTH_USER_MODEL),
        ),
    ]
