# Generated by Django 6.0 on 2026-01-10 16:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Yakkum', max_length=100)),
                ('app_description', models.TextField(blank=True)),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('app_favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('email_from_address', models.EmailField(default='noreply@yakkum.id', max_length=254)),
                ('email_from_name', models.CharField(default='Yakkum', max_length=100)),
                ('session_timeout', models.IntegerField(default=30, help_text='Session timeout in minutes (5-1440)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('password_min_length', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(32)])),
                ('require_email_verification', models.BooleanField(default=False)),
                ('enable_two_factor_auth', models.BooleanField(default=False)),
                ('data_retention_days', models.IntegerField(default=365, help_text='Number of days to retain data (30-3650)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3650)])),
                ('enable_audit_logs', models.BooleanField(default=True)),
                ('survey_auto_approval', models.BooleanField(default=False, help_text='Auto-approve surveys without verification')),
                ('survey_draft_expiry_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(180)])),
                ('default_page_size', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('max_page_size', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)])),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='System is under maintenance. Please try again later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
